### ISSUE TITLE
Swanky Paint not launching on Raspberry Pi 2

### ISSUE THREAD

**Issue by robthez** [xriss/swankypaint#11]
Tried it on both up-to-date wheezy and jessie Raspbian, same results. Launch from command line and get the following error:

The flavour of win is sdl
SDL screen
SDL create
./gamecake.raspi: /home/pi/swankypaint/lua/wetgenes/win/sdl.lua:46: Could not get EGL display
stack traceback:
    [C]: in function 'assert'
    /home/pi/swankypaint/lua/wetgenes/win/sdl.lua:46: in function 'create'
    /home/pi/swankypaint/lua/wetgenes/win.lua:333: in function 'create'
    /home/pi/swankypaint/lua/wetgenes/gamecake/oven.lua:181: in function 'preheat'
    [string "--#!/usr/local/bin/gamecake..."]:25: in function 'func'
    [string "start"]:44: in main chunk
    [C]: at 0x001f7560
    [C]: at 0x0001adc0

**Comment by xriss** [comment]
Strange, maybe something has broken since last I ran it, will set a PI up and test its all still OK.

But in the meantime a couple of possibilities, since this is going wrong at a very basic level of initialization.

Try running under xwin to see if it makes a difference?

Memory Split, myabe the GPU is out of memory as the split is set too low?

**Comment by robthez** [comment]
Ah sorry, I should have been more clear - did it in the terminal from the desktop. Also tried the launch function from the file manager but didn't really expect it to work (and it didn't).

Maybe I'll try from the actual command line and see if that makes a difference.

As for the memory split - that's the default!

**Comment by robthez** [comment]
Now I have a new problem, it crashes after an indeterminate amount of time and seems to disconnect the mouse and keyboard. Happens quickly if the mouse is moved quite fast, tried to see if it would be fine by using the mouse very slowly but it crashed anyway after a while.

**Comment by notshi** [comment]
Just a thought - could this be a power issue? It sounds like the device might not be getting enough power.

Sometimes this might trigger a rainbow square on the screen.

**Comment by robthez** [comment]
Using one of the official Pi power supplies, no rainbow square, properly powered

**Comment by notshi** [comment]
Thanks, will reproduce the same bug in the Pi and hopefully come back with a solution!

**Comment by xriss** [comment]
@robthez 

After some testing I'm beginning to suspect that its a recent update which has broken OpenGL under raspbian.

(Its not working from the command line for me either, same error, so you currently have more success than me)

I have old SD cards that still work but trying new fresh installs and I'm just getting the same EGL fail.


As a test, try building and running this repo as a quick GL test, (not my code and builds fast)

https://github.com/dff180/pishadertoy

This fails for me when trying to open a surface/window hence my suspicion that it is an OS problem.

Also minecraft-pi seems to be broken too, so try that as well.

Right now I'm thinking wait for a raspbian update/fix or downgrade (my PI2 worked when it first shipped)

**Comment by robthez** [comment]
Crikey, sorry for taking too long to get back on this. Got pishadertoy and it's working fine, same with Minecraft Pi.

Have there been updates to swankypaint since November that means I should probably redownload it?

**Comment by xriss** [comment]
@robthez There is a newer version with some fixes attempted for this but its not working on newer raspbian builds (it still works on older versions for me) so that's probably not going to help.

I'm going to build a version against the most recent everything this weekend and see if that helps. Will let you know when that's available to try.

**Comment by xriss** [comment]
@robthez Sorry, still no success, no idea what's been broken but as far as I can tell the previouse vidcore hacks that we had to use no longer works and linking against the apt-get provided SDL2 or a self built SDL2 doesnt work either.

All problems that have only recently arrived for me.

Minecraft is now working in the most recent raspbian jessie so things are getting fixed. Possibly something else strange that I'm doing but when the apt-get supplied SDL2 says it cant find any sort of display smells like a distro/config bug to me.

Sorry, will try again in a little while, or you could just go back to a previously working version of raspbian which is what I've been running since I discovered the updates where broken last year.

**Comment by xriss** [comment]
@robthez OK, tried some more and have managed to get a working SDL2 build using the latest source.

and we can now open a display, hoorah :)

However, it seems that Frame Buffers are broken in the current driver. Nothing I seem to do lets me create them, this is fairly simple opengl code that used to work and still works on other systems. So I figure we are now hitting driver bugs/issues again.

So getting better but still borked.

**Comment by xriss** [comment]
@robthez this update seems to have unbroken things for me, so as suspected I don't think I was actually doing anything wrong...

https://www.raspberrypi.org/blog/another-new-raspbian-release/

Can you try it and see if its working for you?

Its possible I may have broken something my end trying to work out why everything was broken so best if you don't grab a new release for now. I'll look into putting out a new code release soon anyhow since we now have a more contained way of cross compiling using a qemu box.

**Comment by robthez** [comment]
I'll give it a shot when I have a chance this evening, I know there's extra OpenGL work going on at the moment so maybe that was what fixed it.

Thanks for working on it!
