### ISSUE TITLE
Running it on Android (downloaded from Dimeload)

### ISSUE THREAD

**Issue by yuigoto** [xriss/swankypaint#15]
I recently got the Steam version, which runs pretty nicely here. It feels kinda different when you come from PyxelEdit or Aseprite, but it's really a nice one!

I felt that the app totally fits a touch screen, so when I found out about the Android APK on Dimeload I couldn't resist. But the app isn't working in here. :disappointed:

I don't know if it's because I'm running it on a kinda modest hardware (well, I'm always a bit skint, so I can't get my hands on better hardware :sweat_smile:) or if I'm doing something wrong.

But here's how Swanky paint runs on the devices I have in here:
- [Android 4.4.2 - LG GPad 8.3 (v500)](http://i.imgur.com/y2hggJt.png);
- [Android 5.0.1 - LG Spirit (Volt, here in Brazil)](http://i.imgur.com/7Hpich8.png);
- [Android 4.4.2 - Motorola Razr D3](http://i.imgur.com/9UDdR1k.png);

It stays like this forever and the app won't get past this.

Is there something I can do in here? Is it a bug?

Thanks! And congrats on the nice app!

**Comment by xriss** [comment]
Hi there,

Sorry, android is currently suffering form the bitrot. I did actually start looking at patching it up.

Yesterday I adding a .apk to the steam beta[test] builds ( you can find it in /install/*.apk ) It will probably still crash but at least its a later build :)

I broke the android build when I setup the first steam build so I need to go back and look at what's going wrong. It just fell down the list of priorities and got forgotten about. Mostly since the Android version has never been good to use, fat fingers and small screens makes it unusable.

Needs a complete rebuild of the interface even on a big tablet. However since I really want it to work well on cheap windows touch screen tablets such as the linx 8, a touch interface for fat fingers is on the list of things to aim for.

So yeah, let me go poke the android build a little and I'll see if I can spot the problem at least.

**Comment by xriss** [comment]
update the steam beta[test] version probably has a fixed apk in it's /install directory now

**Comment by yuigoto** [comment]
Thanks for the quick reply, Xriss! Sorry for taking a bit to answer (family-related issues, etc. :confused:).

Just installed it and, even with a HD tablet, I can totally get the issue about fingers and stuff. Still, I kinda have this feeling that it's a great app to take on the go too! I also have a cheap Win8 tablet here, I'll try Swanky on it later too.

Thanks again! :)
